import { Typography } from "@mui/material";
import type { NextPage } from "next";
import { useEffect, useState } from "react";
import Typed from "react-typed";

const Home: NextPage = () => {
  let typed: any;

  useEffect(() => {
    if (typed) {
      typed.start();
    }
  }, [typed]);

  return (
    <div>
      <main>
        <section className="mb-5 h-96 flex relative justify-center items-center text-center px-10">
          <Typography variant={"h4"}>
            <Typed
              typedRef={(typedRef: any) => (typed = typedRef)}
              strings={[
                "Welcome.",
                "My name is Adam Kui.",
                "I'm a software developer from Budapest, Hungary.",
                "Take a look around!",
              ]}
              startDelay={500}
              typeSpeed={25}
              backSpeed={5}
              backDelay={1750}
              loop
            />
          </Typography>
          <video
            src="river_loop.mp4"
            autoPlay
            loop
            muted
            className="min-w-full min-h-full object-cover opacity-50 absolute left-0 top-0 h-96"
          />
        </section>
      </main>
    </div>
    /*
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href="https://nextjs.org">Next.js!</a>
        </h1>

        <p className={"font-bold underline"}>
          Get started by editing{" "}
          <code className={styles.code}>pages/index.tsx</code>
        </p>

        <div className={styles.grid}>
          <a href="https://nextjs.org/docs" className={styles.card}>
            <h2>Documentation &rarr;</h2>
            <p>Find in-depth information about Next.js features and API.</p>
          </a>

          <a href="https://nextjs.org/learn" className={styles.card}>
            <h2>Learn &rarr;</h2>
            <p>Learn about Next.js in an interactive course with quizzes!</p>
          </a>

          <a
            href="https://github.com/vercel/next.js/tree/canary/examples"
            className={styles.card}
          >
            <h2>Examples &rarr;</h2>
            <p>Discover and deploy boilerplate example Next.js projects.</p>
          </a>

          <a
            href="https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            className={styles.card}
          >
            <h2>Deploy &rarr;</h2>
            <p>
              Instantly deploy your Next.js site to a public URL with Vercel.
            </p>
          </a>
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{" "}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
    */
  );
};

export default Home;
